#!/usr/bin/env python

import os


extension = '.symlink'
extension_len = len(extension)

current_directory = os.path.dirname(os.path.realpath(__file__))
home_directory = os.getenv('HOME')

for filename in os.listdir(current_directory):
    if filename.endswith(extension):
        file_path = os.path.join(current_directory, filename)
        link_path = os.path.join(home_directory, filename[:-extension_len])

        try:
            os.symlink(file_path, link_path)
        except OSError:
            print '%s already exists' % link_path
        else:
            print 'linked %s' % link_path
